plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

sourceSets {
	gametest {
		compileClasspath += sourceSets.main.output + sourceSets.main.compileClasspath
		runtimeClasspath += sourceSets.main.output + sourceSets.main.runtimeClasspath
	}
}

configurations {
	gametestImplementation.extendsFrom implementation
	gametestRuntimeOnly.extendsFrom runtimeOnly
}

repositories {
	mavenCentral()
	maven { url = 'https://jitpack.io' }
	maven {
		name = 'Fzzy Config'
		url = 'https://maven.fzzyhmstrs.me/'
	}
}

loom {
	mods {
		flatcoloredblocksfabric {
			sourceSet sourceSets.main
		}
		flatcoloredblocksfabric_test {
			sourceSet sourceSets.gametest
		}
	}

	runs {
		gametest {
			inherit server
			name = 'Game Test'
			source sourceSets.gametest
			vmArg '-Dfabric-api.gametest'
			vmArg "-Dfabric-api.gametest.report-file=${layout.buildDirectory.file('gametest-report.xml').get().asFile}"
			runDir = 'build/gametest'
		}

		clientGametest {
			inherit client
			name = 'Client Game Test'
			source sourceSets.gametest
			vmArg '-Dfabric.client.gametest'
			runDir = 'build/client-gametest'
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation("me.fzzyhmstrs:fzzy_config:${project.fzzy_config_version}") {
		exclude group: 'com.terraformersmc', module: 'modmenu'
	}
	implementation 'com.github.westernbear:ChiselsAndBits:v1.3.10'
}

processResources {
	inputs.property 'version', project.version
	filesMatching('fabric.mod.json') {
		expand 'version': project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = 25
}

tasks.named('test') {
	failOnNoDiscoveredTests.set(false)
}

def colorMathCheck = tasks.register('colorMathCheck', JavaExec) {
	dependsOn testClasses
	classpath = sourceSets.test.runtimeClasspath
	mainClass = 'mod.flatcoloredblocks.block.ColorMathCheck'
}

tasks.named('check') {
	dependsOn colorMathCheck
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from('LICENSE') {
		rename { "${it}_${project.base.archivesName.get()}" }
	}
}
