org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
enabled_platforms=fabric,neoforge

fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.2

neoforge_version=26.2.0.71

architectury_version=21.0.7
architectury_plugin_version=3.5-SNAPSHOT
loom_version=1.17-SNAPSHOT
loom.ignoreDependencyLoomVersionValidation=true

mod_version=8.1.2
maven_group=mod.flatcoloredblocks
archives_base_name=flatcoloredblocksrestitched

chiselsandbits_version=1.3.10
fzzy_config_version=0.7.6+26.2
