org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.17

mod_version=8.1.2
maven_group=mod.flatcoloredblocks
archives_base_name=flatcoloredblocksrestitched

fabric_api_version=0.155.2+26.2
fzzy_config_version=0.7.6+26.2
