plugins {
	id 'net.neoforged.moddev' version '2.0.140'
	id 'com.gradleup.shadow'
}

dependencies {
	implementation project(':common')
	implementation "dev.architectury:architectury-neoforge:${rootProject.architectury_version}"
}

configurations {
	shadowBundle {
		canBeResolved = true
		canBeConsumed = false
	}
}

dependencies {
	shadowBundle project(':common')
}

neoForge {
	enable {
		version = rootProject.neoforge_version
	}

	mods {
		flatcoloredblocks {
			sourceSet sourceSets.main
		}
	}

	runs {
		client {
			client()
			programArguments.addAll('--username', 'Dev')
		}

		server {
			server()
		}
	}
}

processResources {
	inputs.property 'version', project.version
	filesMatching('META-INF/neoforge.mods.toml') {
		expand 'version': project.version
	}
}

jar {
	archiveClassifier = 'raw'
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${project.base.archivesName.get()}" }
	}
}

shadowJar {
	dependsOn jar
	mainSpec.sourcePaths.clear()
	from(zipTree(jar.archiveFile))
	configurations = [project.configurations.shadowBundle]
	archiveClassifier = null
}

assemble.dependsOn shadowJar

tasks.named('compileJava').configure {
	dependsOn ':common:classes'
}
